In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [2]:
# 1) FBI
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [3]:
url = 'https://www.fbi.gov/wanted/topten'

In [4]:
response = requests.get(url)
response.status_code # 200 status code means OK!

200

In [5]:
soup = BeautifulSoup(response.content, "html.parser")

In [6]:
soup.select('#query-results-0f737222c5054a81a120bce207b0446a > ul')

[<ul class="full-grid wanted-grid-natural infinity castle-grid-block-xs-2 castle-grid-block-sm-2castle-grid-block-md-3 castle-grid-block-lg-5 dt-grid" style="">
 <li class="portal-type-person castle-grid-block-item">
 <a href="https://www.fbi.gov/wanted/topten/yulan-adonay-archaga-carias">
 <div class="focuspoint" data-base-url="https://www.fbi.gov/wanted/topten/yulan-adonay-archaga-carias/@@images/image/" data-focus-x="0.0866666666667" data-focus-y="-0.0993117160853" data-h="692" data-scale="preview" data-scales-info='{"preview": {"h": 452, "w": 400}, "high": {"h": 1583, "w": 1400}, "thumb": {"h": 144, "w": 128}, "mini": {"h": 226, "w": 200}, "tile": {"h": 72, "w": 64}, "large": {"h": 868, "w": 768}, "icon": {"h": 36, "w": 32}, "listing": {"h": 18, "w": 16}}' data-w="612"><img alt="YULAN ADONAY ARCHAGA CARIAS" class="" src="https://www.fbi.gov/wanted/topten/yulan-adonay-archaga-carias/@@images/image/preview"/></div>
 </a>
 <h3 class="title">
 <a href="https://www.fbi.gov/wanted/topten/yulan-adonay-archaga-carias">YULAN ADONAY ARCHAGA CARIAS</a>
 </h3>
 </li>
 <li class="portal-type-person castle-grid-block-item">
 <a href="https://www.fbi.gov/wanted/topten/bhadreshkumar-chetanbhai-patel">
 <div class="focuspoint" data-base-url="https://www.fbi.gov/wanted/topten/bhadreshkumar-chetanbhai-patel/@@images/image/" data-focus-x="0.0" data-focus-y="-0.0" data-h="600" data-scale="preview" data-scales-info='{"preview": {"h": 533, "w": 400}, "high": {"h": 1866, "w": 1400}, "thumb": {"h": 170, "w": 128}, "mini": {"h": 266, "w": 200}, "tile": {"h": 85, "w": 64}, "large": {"h": 1024, "w": 768}, "icon": {"h": 42, "w": 32}, "listing": {"h": 21, "w": 16}}' data-w="450"><img alt="BHADRESHKUMAR CHETANBHAI PATEL" class="" src="https://www.fbi.gov/wanted/topten/bhadreshkumar-chetanbhai-patel/@@images/image/preview"/></div>
 </a>
 <h3 class="title">
 <a href="https://www.fbi.gov/wanted/topten/bhadreshkumar-chetanbhai-patel">BHADRESHKUMAR CHETANBHAI PATEL</a>
 </h3>
 </li>
 <li class="portal-type-person castle-grid-block-item">
 <a href="https://www.fbi.gov/wanted/topten/alejandro-castillo">
 <div class="focuspoint" data-base-url="https://www.fbi.gov/wanted/topten/alejandro-castillo/@@images/image/" data-focus-x="-0.0322580645161" data-focus-y="-0.144328217008" data-h="692" data-scale="preview" data-scales-info='{"preview": {"h": 494, "w": 400}, "high": {"h": 1730, "w": 1400}, "thumb": {"h": 158, "w": 128}, "mini": {"h": 247, "w": 200}, "tile": {"h": 79, "w": 64}, "large": {"h": 949, "w": 768}, "icon": {"h": 39, "w": 32}, "listing": {"h": 19, "w": 16}}' data-w="560"><img alt="ALEJANDRO ROSALES CASTILLO" class="" src="https://www.fbi.gov/wanted/topten/alejandro-castillo/@@images/image/preview"/></div>
 </a>
 <h3 class="title">
 <a href="https://www.fbi.gov/wanted/topten/alejandro-castillo">ALEJANDRO ROSALES CASTILLO</a>
 </h3>
 </li>
 <li class="portal-type-person castle-grid-block-item">
 <a href="https://www.fbi.gov/wanted/topten/ruja-ignatova">
 <div class="focuspoint" data-base-url="https://www.fbi.gov/wanted/topten/ruja-ignatova/@@images/image/" data-focus-x="-0.0933333333333" data-focus-y="-0.0320872369214" data-h="692" data-scale="preview" data-scales-info='{"preview": {"h": 428, "w": 400}, "high": {"h": 1499, "w": 1400}, "thumb": {"h": 137, "w": 128}, "mini": {"h": 214, "w": 200}, "tile": {"h": 68, "w": 64}, "large": {"h": 822, "w": 768}, "icon": {"h": 34, "w": 32}, "listing": {"h": 17, "w": 16}}' data-w="646"><img alt="RUJA IGNATOVA" class="" src="https://www.fbi.gov/wanted/topten/ruja-ignatova/@@images/image/preview"/></div>
 </a>
 <h3 class="title">
 <a href="https://www.fbi.gov/wanted/topten/ruja-ignatova">RUJA IGNATOVA</a>
 </h3>
 </li>
 <li class="portal-type-person castle-grid-block-item">
 <a href="https://www.fbi.gov/wanted/topten/arnoldo-jimenez">
 <div class="focuspoint" data-base-url="https://www.fbi.gov/wanted/topten/arnoldo-jimenez/@@images/image/" data-focus-x="-0.123333333333" data-focus-y="0.03466668023" data-h="711" data-scale="preview" data-scales-info='{"preview": {"h": 600, "w": 400}, "high": {"h": 2100, "w": 1400}, "thumb": {"h": 191, "w": 127}, "mini": {"h": 300, "w": 200}, "tile": {"h": 95, "w": 63}, "large": {"h": 1152, "w": 768}, "icon": {"h": 47, "w": 31}, "listing": {"h": 23, "w": 15}}' data-w="474"><img alt="ARNOLDO JIMENEZ" class="" src="https://www.fbi.gov/wanted/topten/arnoldo-jimenez/@@images/image/preview"/></div>
 </a>
 <h3 class="title">
 <a href="https://www.fbi.gov/wanted/topten/arnoldo-jimenez">ARNOLDO JIMENEZ</a>
 </h3>
 </li>
 <li class="portal-type-person castle-grid-block-item">
 <a href="https://www.fbi.gov/wanted/topten/omar-alexander-cardenas">
 <div class="focuspoint" data-base-url="https://www.fbi.gov/wanted/topten/omar-alexander-cardenas/@@images/image/" data-focus-x="-0.0266666666667" data-focus-y="-0.0495260518874" data-h="692" data-scale="preview" data-scales-info='{"preview": {"h": 562, "w": 400}, "high": {"h": 1969, "w": 1400}, "thumb": {"h": 180, "w": 128}, "mini": {"h": 281, "w": 200}, "tile": {"h": 90, "w": 64}, "large": {"h": 1080, "w": 768}, "icon": {"h": 45, "w": 32}, "listing": {"h": 22, "w": 16}}' data-w="492"><img alt="OMAR ALEXANDER CARDENAS" class="" src="https://www.fbi.gov/wanted/topten/omar-alexander-cardenas/@@images/image/preview"/></div>
 </a>
 <h3 class="title">
 <a href="https://www.fbi.gov/wanted/topten/omar-alexander-cardenas">OMAR ALEXANDER CARDENAS</a>
 </h3>
 </li>
 <li class="portal-type-person castle-grid-block-item">
 <a href="https://www.fbi.gov/wanted/topten/alexis-flores">
 <div class="focuspoint" data-base-url="https://www.fbi.gov/wanted/topten/alexis-flores/@@images/image/" data-focus-x="-0.0563106796117" data-focus-y="0.0262599349711" data-h="692" data-scale="preview" data-scales-info='{"preview": {"h": 537, "w": 400}, "high": {"h": 1881, "w": 1400}, "thumb": {"h": 171, "w": 128}, "mini": {"h": 268, "w": 200}, "tile": {"h": 85, "w": 64}, "large": {"h": 1031, "w": 768}, "icon": {"h": 42, "w": 32}, "listing": {"h": 21, "w": 16}}' data-w="515"><img alt="ALEXIS FLORES" class="" src="https://www.fbi.gov/wanted/topten/alexis-flores/@@images/image/preview"/></div>
 </a>
 <h3 class="title">
 <a href="https://www.fbi.gov/wanted/topten/alexis-flores">ALEXIS FLORES</a>
 </h3>
 </li>
 <li class="portal-type-person castle-grid-block-item">
 <a href="https://www.fbi.gov/wanted/topten/jose-rodolfo-villarreal-hernandez">
 <div class="focuspoint" data-base-url="https://www.fbi.gov/wanted/topten/jose-rodolfo-villarreal-hernandez/@@images/image/" data-focus-x="0.0" data-focus-y="-0.0" data-h="692" data-scale="preview" data-scales-info='{"preview": {"h": 532, "w": 400}, "high": {"h": 1863, "w": 1400}, "thumb": {"h": 170, "w": 128}, "mini": {"h": 266, "w": 200}, "tile": {"h": 85, "w": 64}, "large": {"h": 1022, "w": 768}, "icon": {"h": 42, "w": 32}, "listing": {"h": 21, "w": 16}}' data-w="520"><img alt="JOSE RODOLFO VILLARREAL-HERNANDEZ" class="" src="https://www.fbi.gov/wanted/topten/jose-rodolfo-villarreal-hernandez/@@images/image/preview"/></div>
 </a>
 <h3 class="title">
 <a href="https://www.fbi.gov/wanted/topten/jose-rodolfo-villarreal-hernandez">JOSE RODOLFO VILLARREAL-HERNANDEZ</a>
 </h3>
 </li>
 <li class="portal-type-person castle-grid-block-item">
 <a href="https://www.fbi.gov/wanted/topten/michael-james-pratt">
 <div class="focuspoint" data-base-url="https://www.fbi.gov/wanted/topten/michael-james-pratt/@@images/image/" data-focus-x="-0.0466666666667" data-focus-y="-0.099999988202" data-h="692" data-scale="preview" data-scales-info='{"preview": {"h": 517, "w": 400}, "high": {"h": 1810, "w": 1400}, "thumb": {"h": 165, "w": 128}, "mini": {"h": 258, "w": 200}, "tile": {"h": 82, "w": 64}, "large": {"h": 993, "w": 767}, "icon": {"h": 41, "w": 32}, "listing": {"h": 20, "w": 16}}' data-w="535"><img alt="MICHAEL JAMES PRATT" class="" src="https://www.fbi.gov/wanted/topten/michael-james-pratt/@@images/image/preview"/></div>
 </a>
 <h3 class="title">
 <a href="https://www.fbi.gov/wanted/topten/michael-james-pratt">MICHAEL JAMES PRATT</a>
 </h3>
 </li>
 <li class="portal-type-person castle-grid-block-item">
 <a href="https://www.fbi.gov/wanted/topten/rafael-caro-quintero">
 <div class="focuspoint" data-base-url="https://www.fbi.gov/wanted/topten/rafael-caro-quintero/@@images/image/" data-focus-x="0.2" data-focus-y="-0.103592081851" data-h="692" data-scale="preview" data-scales-info='{"preview": {"h": 375, "w": 399}, "high": {"h": 1312, "w": 1400}, "thumb": {"h": 120, "w": 128}, "mini": {"h": 187, "w": 199}, "tile": {"h": 60, "w": 64}, "large": {"h": 720, "w": 768}, "icon": {"h": 30, "w": 32}, "listing": {"h": 15, "w": 16}}' data-w="738"><img alt="RAFAEL CARO-QUINTERO" class="" src="https://www.fbi.gov/wanted/topten/rafael-caro-quintero/@@images/image/preview"/></div>
 </a>
 <h3 class="title">
 <a href="https://www.fbi.gov/wanted/topten/rafael-caro-quintero">RAFAEL CARO-QUINTERO</a>
 </h3>
 </li>
 </ul>]

In [7]:
soup.select("h3 > a")

[<a href="https://www.fbi.gov/wanted/topten/yulan-adonay-archaga-carias">YULAN ADONAY ARCHAGA CARIAS</a>,
 <a href="https://www.fbi.gov/wanted/topten/bhadreshkumar-chetanbhai-patel">BHADRESHKUMAR CHETANBHAI PATEL</a>,
 <a href="https://www.fbi.gov/wanted/topten/alejandro-castillo">ALEJANDRO ROSALES CASTILLO</a>,
 <a href="https://www.fbi.gov/wanted/topten/ruja-ignatova">RUJA IGNATOVA</a>,
 <a href="https://www.fbi.gov/wanted/topten/arnoldo-jimenez">ARNOLDO JIMENEZ</a>,
 <a href="https://www.fbi.gov/wanted/topten/omar-alexander-cardenas">OMAR ALEXANDER CARDENAS</a>,
 <a href="https://www.fbi.gov/wanted/topten/alexis-flores">ALEXIS FLORES</a>,
 <a href="https://www.fbi.gov/wanted/topten/jose-rodolfo-villarreal-hernandez">JOSE RODOLFO VILLARREAL-HERNANDEZ</a>,
 <a href="https://www.fbi.gov/wanted/topten/michael-james-pratt">MICHAEL JAMES PRATT</a>,
 <a href="https://www.fbi.gov/wanted/topten/rafael-caro-quintero">RAFAEL CARO-QUINTERO</a>]

In [8]:
names = []

num_iter = len(soup.select("h3 > a"))

names_list = soup.select("h3 > a")

for i in range(num_iter):
    names.append(names_list[i].get_text())

In [9]:
top_10_wanted = pd.DataFrame({'names':names})

In [10]:
top_10_wanted.head(10)

                               names
0        YULAN ADONAY ARCHAGA CARIAS
1     BHADRESHKUMAR CHETANBHAI PATEL
2         ALEJANDRO ROSALES CASTILLO
3                      RUJA IGNATOVA
4                    ARNOLDO JIMENEZ
5            OMAR ALEXANDER CARDENAS
6                      ALEXIS FLORES
7  JOSE RODOLFO VILLARREAL-HERNANDEZ
8                MICHAEL JAMES PRATT
9               RAFAEL CARO-QUINTERO

In [11]:
#-------------------------#

In [28]:
#2) LANGUAGES

#Display the top 10 languages by number of native speakers stored in a pandas dataframe

In [29]:
url = 'https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers'

In [30]:
response = requests.get(url)
response.status_code # 200 status code means OK!

200

In [31]:
soup_2 = BeautifulSoup(response.content, "html.parser")

In [32]:
soup_2.select("tbody > tr > td > a.mw-redirect")

[<a class="mw-redirect" href="/wiki/ISO_639:cmn" title="ISO 639:cmn">Mandarin Chinese</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:spa" title="ISO 639:spa">Spanish</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:eng" title="ISO 639:eng">English</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:hin" title="ISO 639:hin">Hindi</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:ben" title="ISO 639:ben">Bengali</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:por" title="ISO 639:por">Portuguese</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:rus" title="ISO 639:rus">Russian</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:jpn" title="ISO 639:jpn">Japanese</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:yue" title="ISO 639:yue">Yue Chinese</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:vie" title="ISO 639:vie">Vietnamese</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:mar" title="ISO 639:mar">Marathi</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:tel" title="ISO 639:tel">Telugu</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:tur" title="ISO 639:tur">Turkish</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:wuu" title="ISO 639:wuu">Wu Chinese</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:kor" title="ISO 639:kor">Korean</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:fra" title="ISO 639:fra">French</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:tam" title="ISO 639:tam">Tamil</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:deu" title="ISO 639:deu">Standard German</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:arz" title="ISO 639:arz">Egyptian Spoken Arabic</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:urd" title="ISO 639:urd">Urdu</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:jav" title="ISO 639:jav">Javanese</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:pnb" title="ISO 639:pnb">Western Punjabi</a>,
 <a class="mw-redirect" href="/wiki/Eastern_Punjabi_language" title="Eastern Punjabi language">Eastern Punjabi</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:ita" title="ISO 639:ita">Italian</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:guj" title="ISO 639:guj">Gujarati</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:pes" title="ISO 639:pes">Iranian Persian</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:bho" title="ISO 639:bho">Bhojpuri</a>,
 <a class="mw-redirect" href="/wiki/ISO_639:hau" title="ISO 639:hau">Hausa</a>,
 <a class="mw-redirect" href="/wiki/Arabic_language" title="Arabic language">Arabic</a>,
 <a class="mw-redirect" href="/wiki/Hindi_language" title="Hindi language">Hindi</a>]

In [37]:
# parse data from the html into a beautifulsoup object

language=soup_2.find('table',{'class':"wikitable"})

In [38]:
df = pd.read_html(str(language))

# convert list to dataframe
df=pd.DataFrame(df[0])
df

,Language,Native speakers(millions),Language family,Branch
0,"Mandarin Chinese(incl. Standard Chinese, but e...",920.0,Sino-Tibetan,Sinitic
1,Spanish,475.0,Indo-European,Romance
2,English,373.0,Indo-European,Germanic
3,Hindi(excl. Urdu),344.0,Indo-European,Indo-Aryan
4,Bengali,234.0,Indo-European,Indo-Aryan
5,Portuguese,232.0,Indo-European,Romance
6,Russian,154.0,Indo-European,Balto-Slavic
7,Japanese,125.0,Japonic,Japanese
8,Yue Chinese(incl. Cantonese),85.2,Sino-Tibetan,Sinitic
9,Vietnamese,84.6,Austroasiatic,Vietic
10,Marathi,83.1,Indo-European,Indo-Aryan
11,Telugu,82.7,Dravidian,South-Central
12,Turkish,82.2,Turkic,Oghuz
13,Wu Chinese(incl. Shanghainese),81.8,Sino-Tibetan,Sinitic
14,Korean,81.7,Koreanic,language isolate
15,French,79.9,Indo-European,Romance
16,Tamil,78.4,Dravidian,South
17,Standard German,75.6,Indo-European,Germanic
18,Egyptian Spoken Arabic(excl. Saʽidi Arabic),74.8,Afroasiatic,Semitic
19,Urdu(excl. Hindi),70.2,Indo-European,Indo-Aryan
20,Javanese,68.3,Austronesian,Malayo-Polynesian
21,Western Punjabi(excl. Eastern Punjabi),66.4,Indo-European,Indo-Aryan
22,Italian,64.8,Indo-European,Romance
23,Gujarati,57.0,Indo-European,Indo-Aryan
24,Iranian Persian(excl. Dari and Tajik),56.4,Indo-European,Iranian
25,Bhojpuri,52.3,Indo-European,Indo-Aryan
26,Hausa,50.8,Afroasiatic,Chadic

In [20]:
# 3) Display the 20 latest earthquakes info (date, time, latitude, longitude and region name) by the EMSC as a pandas dataframe:

In [21]:
 url = "https://www.emsc-csem.org/Earthquake/"

In [22]:
response = requests.get(url)
response.status_code # 200 status code means OK!

200

In [23]:
soup_3 = BeautifulSoup(response.content, "html.parser")

In [24]:
#soup_3.select("body")

In [25]:
# to get the latitude + longitude
soup_3.select('td.tabev1')

[<td class="tabev1">38.79 </td>,
 <td class="tabev1">122.76 </td>,
 <td class="tabev1">7.11 </td>,
 <td class="tabev1">129.97 </td>,
 <td class="tabev1">8.71 </td>,
 <td class="tabev1">116.07 </td>,
 <td class="tabev1">15.98 </td>,
 <td class="tabev1">41.72 </td>,
 <td class="tabev1">9.21 </td>,
 <td class="tabev1">124.22 </td>,
 <td class="tabev1">9.65 </td>,
 <td class="tabev1">121.54 </td>,
 <td class="tabev1">33.40 </td>,
 <td class="tabev1">116.39 </td>,
 <td class="tabev1">41.17 </td>,
 <td class="tabev1">73.20 </td>,
 <td class="tabev1">19.57 </td>,
 <td class="tabev1">156.15 </td>,
 <td class="tabev1">35.22 </td>,
 <td class="tabev1">23.17 </td>,
 <td class="tabev1">23.49 </td>,
 <td class="tabev1">68.96 </td>,
 <td class="tabev1">0.82 </td>,
 <td class="tabev1">121.62 </td>,
 <td class="tabev1">17.96 </td>,
 <td class="tabev1">66.90 </td>,
 <td class="tabev1">19.17 </td>,
 <td class="tabev1">155.50 </td>,
 <td class="tabev1">32.75 </td>,
 <td class="tabev1">71.77 </td>,
 <td class="tabev1">6.71 </td>,
 <td class="tabev1">125.91 </td>,
 <td class="tabev1">11.22 </td>,
 <td class="tabev1">85.83 </td>,
 <td class="tabev1">8.98 </td>,
 <td class="tabev1">124.21 </td>,
 <td class="tabev1">35.53 </td>,
 <td class="tabev1">3.83 </td>,
 <td class="tabev1">41.99 </td>,
 <td class="tabev1">7.33 </td>,
 <td class="tabev1">39.37 </td>,
 <td class="tabev1">26.26 </td>,
 <td class="tabev1">39.39 </td>,
 <td class="tabev1">26.19 </td>,
 <td class="tabev1">11.83 </td>,
 <td class="tabev1">125.27 </td>,
 <td class="tabev1">19.39 </td>,
 <td class="tabev1">155.44 </td>,
 <td class="tabev1">33.04 </td>,
 <td class="tabev1">148.99 </td>,
 <td class="tabev1">39.38 </td>,
 <td class="tabev1">26.22 </td>,
 <td class="tabev1">40.60 </td>,
 <td class="tabev1">21.61 </td>,
 <td class="tabev1">39.92 </td>,
 <td class="tabev1">120.75 </td>,
 <td class="tabev1">36.60 </td>,
 <td class="tabev1">121.20 </td>,
 <td class="tabev1">21.74 </td>,
 <td class="tabev1">68.62 </td>,
 <td class="tabev1">59.37 </td>,
 <td class="tabev1">25.68 </td>,
 <td class="tabev1">39.36 </td>,
 <td class="tabev1">26.27 </td>,
 <td class="tabev1">17.95 </td>,
 <td class="tabev1">67.09 </td>,
 <td class="tabev1">47.19 </td>,
 <td class="tabev1">76.52 </td>,
 <td class="tabev1">46.31 </td>,
 <td class="tabev1">8.11 </td>,
 <td class="tabev1">15.73 </td>,
 <td class="tabev1">96.39 </td>,
 <td class="tabev1">39.31 </td>,
 <td class="tabev1">26.28 </td>,
 <td class="tabev1">37.25 </td>,
 <td class="tabev1">177.25 </td>,
 <td class="tabev1">39.31 </td>,
 <td class="tabev1">26.14 </td>,
 <td class="tabev1">17.97 </td>,
 <td class="tabev1">66.98 </td>,
 <td class="tabev1">18.92 </td>,
 <td class="tabev1">65.14 </td>,
 <td class="tabev1">42.90 </td>,
 <td class="tabev1">145.20 </td>,
 <td class="tabev1">25.18 </td>,
 <td class="tabev1">27.74 </td>,
 <td class="tabev1">8.97 </td>,
 <td class="tabev1">111.13 </td>,
 <td class="tabev1">8.07 </td>,
 <td class="tabev1">125.85 </td>,
 <td class="tabev1">39.37 </td>,
 <td class="tabev1">26.25 </td>,
 <td class="tabev1">37.57 </td>,
 <td class="tabev1">177.73 </td>,
 <td class="tabev1">14.73 </td>,
 <td class="tabev1">145.62 </td>,
 <td class="tabev1">32.26 </td>,
 <td class="tabev1">71.76 </td>,
 <td class="tabev1">18.84 </td>,
 <td class="tabev1">74.11 </td>]

In [26]:
#initialize empty lists
date_time = []
latitude = []
longitude = []
depth = []
magnitude = []
region_name = []
latitude_SN = []
longitude_EW = []

# define the number of iterations of our for loop
# by checking how many elements are in the retrieved result set
# (this is equivalent but more robust than just explicitly defining 250 iterations)
num_iter = len(soup_3.select('td.tabev5'))

date_time_list = soup_3.select('b > a')
region_name_list = soup_3.select('td.tb_region')
depth_list = soup_3.select('td.tabev3')

latitude_list = soup_3.select('td.tabev1')
longitude_list = soup_3.select('td.tabev1')

latitude_SN_list = soup_3.select('td.tabev2')
longitude_EW_list = soup_3.select('td.tabev2')
magnitude_list = soup_3.select('td.tabev2')

# iterate through the result set and retrieve all the data
for i in range(num_iter):
    date_time.append(date_time_list[i].get_text())
    depth.append(depth_list[i].get_text())
    region_name.append(region_name_list[i].get_text())
    
for i in range(0,len(soup_3.select('td.tabev5'))*2,2):
    latitude.append(latitude_list[i].get_text())
    longitude.append(longitude_list[i+1].get_text())

for i in range(0,len(soup_3.select('td.tabev5'))*3,3):
    latitude_SN.append(latitude_SN_list[i].get_text())
    longitude_EW.append(longitude_EW_list[i+1].get_text())
    magnitude.append(magnitude_list[i+2].get_text())

In [27]:
# each list becomes a column
top_20_earthquakes = pd.DataFrame({"date & time":date_time,
                       "latitude degrees":latitude,
                       "latitude SN":latitude_SN,
                       "longitude degrees":longitude,
                       "longitude EW":longitude_EW,
                       "depth":depth,
                       "magnitude":magnitude,
                       "region":region_name,
                      })
top_20_earthquakes.head(10)

,date & time,latitude degrees,latitude SN,longitude degrees,longitude EW,depth,magnitude,region
0,2023-01-09 17:49:05.0,38.79,N,122.76,W,2,2.8,NORTHERN CALIFORNIA
1,2023-01-09 17:47:36.4,7.11,S,129.97,E,115,7.4,"KEPULAUAN BABAR, INDONESIA"
2,2023-01-09 17:32:25.0,8.71,S,116.07,E,70,3.2,"LOMBOK REGION, INDONESIA"
3,2023-01-09 17:31:12.3,15.98,N,41.72,E,2,4.7,RED SEA
4,2023-01-09 17:17:19.0,9.21,S,124.22,E,49,3.6,TIMOR REGION
5,2023-01-09 17:15:51.0,9.65,S,121.54,E,30,2.9,SAVU SEA
6,2023-01-09 16:59:36.4,33.40,N,116.39,W,2,2.0,SOUTHERN CALIFORNIA
7,2023-01-09 16:52:04.5,41.17,N,73.20,E,4,3.8,KYRGYZSTAN
8,2023-01-09 16:48:09.2,19.57,N,156.15,W,35,2.8,"HAWAII REGION, HAWAII"
9,2023-01-09 16:47:50.3,35.22,N,23.17,E,30,3.1,"CRETE, GREECE"